import { Backend } from "../../common.slint";
import { ListViewBase } from "../../components/list_view.slint";
import { CoreSetting, CoreSettingType } from "types.slint";
import { Icons } from "../../icons.slint";
import { ListView } from "std-widgets.slint";

component ListBox {
    in-out property <int> index;
    in property <[string]> choices;
    in property <bool> focused;

    private property <length> item-height: i-area.viewport-height / choices.length;

    callback on-changed();

    HorizontalLayout {
        spacing: 2px;

        Image {
            source: Icons.left-caret;
            visible: focused;
            colorize: #000;
        }

        i-area := Flickable {
            viewport-y: -root.item-height * root.index;
            viewport-height: i-items.min-height;
            height: item-height;
            width: i-items.min-width;

            i-items := VerticalLayout {
                width: self.min-width;
                for choice[i] in root.choices: child-items := Text {
                    text: choice;
                    horizontal-alignment: right;
                }
            }
        }

        Image {
            source: Icons.right-caret;
            visible: focused;
            colorize: #000;
        }
    }

    if focused: FocusScope {
        init => {
            self.focus();
        }
        key-pressed(event) => {
            if !focused {
                return reject;
            }
            if event.text == Key.LeftArrow {
                root.index = max(root.index - 1, 0);
                on-changed();
                return accept;
            }
            if event.text == Key.RightArrow {
                root.index = min(root.index + 1, root.choices.length - 1);
                on-changed();
                return accept;
            }
            reject
        }
    }
}

export component CoreSettingListItem {
    in-out property <CoreSetting> item;
    in property <bool> selected;

    i-highlight := Rectangle {
        width: root.width;
        height: root.height;
        border-width: 1px;
        border-color: selected ? black : transparent;
    }

    // i-popup := PopupWindow {
    //     Rectangle {
    //         height: 100%;
    //         width: 100%;
    //         border-width: 1px;
    //         border-color: black;
    //         background: white;
    //     }

    //     x: 0;
    //     y: -root.absolute-position.y + 8px;
    //     height: i-layout.min-height;
    //     width: i-layout.min-width;

    //     i-layout := VerticalLayout {
    //         padding: 4px;
    //         for choice in root.item.choices: Text {
    //             text: choice;
    //         }
    //     }

    //     forward-focus: i-focus-scope;
    //     i-focus-scope := FocusScope {
    //         key-released(event) => {
    //             if (event.text == "x") {
    //                 parent.close();
    //                 return accept;
    //             }
    //             reject
    //         }
    //     }
    // }

    if selected: FocusScope {
        init => {
            self.focus();
        }
        key-pressed(event) => {
            if event.text == "a" {
                handle-selected();
            }
            reject
        }
    }

    public function handle-selected() {
        if item.type == CoreSettingType.action {
            Backend.game-settings-set(item.id, item.value);
        } else if item.type == CoreSettingType.checkbox {
            item.value = (item.value == 0) ? 1 : 0;
            Backend.game-settings-set(item.id, item.value);
        }
    }

    min-width: i-text.min-width;
    min-height: i-text.min-height + 2px;

    i-text := Text {
        x: 4px;
        text: item.label;
        vertical-alignment: center;
        horizontal-alignment: left;
        overflow: elide;
    }

    if item.type == CoreSettingType.checkbox: Rectangle {
        background: white;
        x: parent.width - self.width - 4px;
        width: self.height;
        height: parent.height - 4px;
        border-color: black;
        border-width: 1px;

        if (item.value != 0): Rectangle {
            x: 2px;
            y: 2px;
            width: parent.width - 4px;
            height: parent.height - 4px;
            background: gray;
        }
    }

    if item.type == CoreSettingType.list: ListBox {
        x: parent.width - self.width - 4px;
        index: item.value;
        choices: item.choices;
        focused: root.selected;
        on-changed => {
            item.value = self.index;
            Backend.game-settings-set(item.id, item.value);
        }
    }

    @children
}

export component CoreSettingListBase inherits ListView {
    in property <[CoreSetting]> model: Backend.core-settings;
    in-out property <int> current-item: 0;

    callback current-item-changed(current-item: int);

    public function set-current-item(index: int) {
        if index < 0 || index >= model.length || index == root.current-item {
            return;
        }
        bring-into-view(index);

        current-item = index;
        focus-item = index;
        current-item-changed(current-item);
    }

    private property <length> item-height: self.viewport-height / self.model.length;
    private property <int> into-view-item: 0;
    private property <length> into-view-item-y: root.item-y(root.into-view-item);
    private property <length> current-item-y: root.item-y(root.focus-item);
    private property <int> focus-item: 0;
    private property <bool> has-item-been-selected: false;

    vertical-scrollbar-policy: always-off;
    horizontal-scrollbar-policy: always-off;

    pure function item-y(index: int) -> length {
        return root.viewport-y + index * root.item-height;
    }

    pure function item-at-y(y: length) -> int {
        return min(root.model.length - 1, max(0, round(y / root.item-height)));
    }

    function bring-into-view(index: int) {
        if (index < 0 || index >= model.length) {
            return;
        }
        into-view-item = index;

        if (into-view-item-y < 0) {
            self.viewport-y += 0 - into-view-item-y;
        }
        if (into-view-item-y + item-height > self.visible-height) {
            self.viewport-y -= into-view-item-y + item-height - self.visible-height;
        }
    }

    public function focus-up() {
        root.set-focus-item(root.focus-item - 1);
    }

    public function focus-down() {
        root.set-focus-item(root.focus-item + 1);
    }

    protected function select-focus-item() {
        root.set-current-item(root.focus-item);
    }

    protected function set-focus-item(index: int) {
        root.focus-item = min(root.model.length - 1, max(0, index));
        root.bring-into-view(root.focus-item);
        root.select-focus-item();
    }

    for item[index] in root.model: CoreSettingListItem {
        height: 20px;
        item: item;
        selected: index == root.current-item;
    }
}

export component CoreSettingList {
    forward-focus: i-focus-scope;

    i-focus-scope := FocusScope {
        i-list := CoreSettingListBase {
            width: 100%;
            height: 100%;
        }

        key-pressed(event) => {
            if (event.text == Key.UpArrow) {
                i-list.focus-up();
                return accept;
            } else if (event.text == Key.DownArrow) {
                i-list.focus-down();
                return accept;
            }
            reject
        }
    }
}
